### ISSUE TITLE
Tilde "~" Key Does Not Work in dbrowse

### ISSUE THREAD

**Issue by amarz45** [clamiax/scripts#4]
Using the `dbrowse` script, you can enter any file or directory. Even using `..` and `.` works. But using `~` doesn't work for some reason. I think the reason is because it is being wrapped in quotes. This seems like a problem with Dmenu but I'm not sure how I can work around this.

```sh
cd "~"
cd: no such file or directory: ~
cd ~ # This works
```

**Comment by amarz45** [comment]
I found an easy fix with `sed`: `sed 's@^~@/home/'"$USER"'@'`.

**Comment by bitsmanent** [comment]
I managed to make it works in be75e98 by allow shell expansions. This way you may also use `$HOME` or even `$(dirname "$MAIL")` if you ever need.
